version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ghost
file_exists_behavior: RETAIN
hooks:
  BeforeInstall:
    - location: scripts/app-stop.sh
      runas: ubuntu
      timeout: 300
  AfterInstall:
    - location: scripts/app-install.sh
      runas: ubuntu
      timeout: 600
  ApplicationStart:
    - location: scripts/app-start.sh
      runas: ubuntu
      timeout: 300
